version: '3'

silent: true

tasks:

  build:
    desc: Builds the application
    cmds:
      - cmd: mvn compile

  clean:
    desc: Cleans built artefacts
    cmds:
      - cmd: rm -rf log
      - cmd: mvn clean

  container:
    desc: Rebuilds the Docker container
    cmds:
      - cmd: ./scripts/container.sh

  composer:
    desc: Rebuilds the Docker container using docker-compose
    cmds:
      - cmd: ./scripts/composer.sh

  package:
    desc: Packages the application
    cmds:
      - cmd: mvn package

  test:
    desc: Executes all tests
    cmds:
      - cmd: mvn test

  run:
    desc: Runs the server locally using Maven
    cmds:
      - cmd: mvn compile exec:java

  serve:
    desc: Starts the server locally from JAR
    cmds:
      - cmd: mvn package
      - cmd: java -jar ./target/server-1.0.0.jar
