version: '3'

silent: true

tasks:

  build:
    desc: Builds the application
    cmds:
      - cmd: mvn compile

  clean:
    desc: Cleans built artefacts
    cmds:
      - cmd: mvn clean

  container:
    desc: Rebuilds the Docker container
    cmds:
      - cmd: ./scripts/container.sh

  package:
    desc: Packages the application
    cmds:
      - cmd: mvn package

  test:
    desc: Runs all tests
    cmds:
      - cmd: mvn test