app:
  name: "Java RPC server for ÐecisionToolkit"
  version: 1.0.1

spring:
  main:
    banner-mode: off
  profiles:
    active: prod
  web:
    resources:
      add-mappings: false

server:
  port: 22023
